fix: remove orphaned .pdkignore.erb template
Template references @configs['required'] but no .pdkignore config
section exists in config_defaults.yml. VDK's template rendering
crashes with NoMethodError: undefined method '+' for nil:NilClass.

This was a PDK leftover not used by VDK.